nerd_config.json as input file
IslasGECI/nerd pull request #23
Opened 2022-01-12 00:13 UTC by islasfernando

Creé un archivo JSON para ingresar los diferentes archivos de tracmap y sus respectivos parámetros los cuales podemos cambiar para cada archivo.

El archivo de configuración tiene la forma de:

```json
{
    "name": "nerd-input-data",
    "output_path": "outputs",
    "spatial_resolution": 2,
    "input_calibration_data": "../tests/data/expected_calibration_data.csv",
    "resources": [
        {
            "input_data_path": "data/multi_files/041220-001.txt",
            "swap_width": 30,
            "aperture_diameter": 90,
            "density_function": "normal"
        },
        {
            "input_data_path": "data/multi_files/041220-002.txt",
            "swap_width": 70,
            "aperture_diameter": 95,
            "density_function": "normal"
        },
        {
            "input_data_path": "data/multi_files/041220-003.txt",
            "swap_width": 175,
            "aperture_diameter": 100,
            "density_function": "normal"
        }
    ]
}
```

2022-01-12 16:53 UTC, islasfernando commented
Hola @devarops, este sería el Pull Request. Ya está el ejemplo corriendo usando el json de configuración en el notebook `examples/tiling_demo.ipynb`.

2022-01-21 18:38 UTC, devarops requested changes
¿Por favor podríamos erradicar a los mutantes? No hay mutantes en la develop.

2022-01-21 21:06 UTC, islasfernando commented
> ¿Por favor podríamos erradicar a los mutantes? No hay mutantes en la develop.

@devarops no hay cambios/sugerencias de cambio en el formato o funcionalidad para antes de rehacer las pruebas?

2022-01-21 21:43 UTC, devarops commented
Me gustó la forma del archivo de configuración 👍

2022-01-21 21:50 UTC, devarops requested changes
Excelente trabajo @islasfernando. Me gustó mucho el formato del JSON.

- [ ] Cambia el nombre del método `calculate_total_density_multi_file` por `_calculate_total_density_from_multi_file`
- [ ] Cambia del método `calculate_total_density` por `_calculate_total_density_from_single_dictionary`
- [ ] Limpia el notebook `tiling_demo.ipynb` para que no tengan errores ni celdas vacías y mejora el formato para que se vea presentable

2022-01-21 21:51 UTC, devarops commented
¿`calculate_total_density_multi_file` usa `calculate_total_density` en un ciclo o algo así?

2022-01-21 22:01 UTC, islasfernando commented
> ¿`calculate_total_density_multi_file` usa `calculate_total_density` en un ciclo o algo así?

No exáctamente, lo intenté hacer así pero no supe como, quizá refactorizando se puedan fusionar. Actualmente es independiente pero contiene código repetido. 

Mi idea era si el JSON es correcto, y el funcionamiento también significaría que: 'Nerd_multifile' y 'calculate_total_density_multi_file' hacen su trabajo correctamente. Si es así, pensaba borrar las anteriores: `Nerd` y `calculate_total_density` para quedarnos con sólo una 1 forma de correr el NERD (Usando el nerd_config.json)

Queremos poder correr el NERD metiendo un diccionario, para 1 sólo archivo y parámetros fijos?

2022-01-24 19:18 UTC, devarops commented
@xwalls ¿Por favor podrías erradicar los mutantes de este PR?

2022-01-24 22:45 UTC, islasfernando commented
Estado actual de mutantes: ⠙ 384/384  🎉 348  ⏰ 0  🤔 0  🙁 36  🔇 0

Faltan pruebas para:

- [ ] [check_output_directory](https://github.com/IslasGECI/nerd/blob/de43249c5aebb5cccb1301a97d179a6be5a20431/nerd/io/import_data.py#L34)
- [ ] [select_parameters_by_index](https://github.com/IslasGECI/nerd/blob/de43249c5aebb5cccb1301a97d179a6be5a20431/nerd/io/import_data.py#L61)
- [ ] [create_df_list](https://github.com/IslasGECI/nerd/blob/de43249c5aebb5cccb1301a97d179a6be5a20431/nerd/io/import_data.py#L48)
- [ ] [import_multifile_tracmap](https://github.com/IslasGECI/nerd/blob/de43249c5aebb5cccb1301a97d179a6be5a20431/nerd/io/import_data.py#L39)
- [ ] [Nerd](https://github.com/IslasGECI/nerd/blob/de43249c5aebb5cccb1301a97d179a6be5a20431/nerd/io/Nerd.py#L16)

2022-02-01 17:43 UTC, xwalls commented
![image](https://media.giphy.com/media/xT9DPxPZnDcBMX6tAk/giphy.gif)

2022-02-01 17:44 UTC, xwalls approved these changes

2022-02-01 17:45 UTC, merged